sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
language: rust
rust: nightly
cache: cargo
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo doc
after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo --verify
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/fc22c02441fe92b9dda0
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: Afu8edoY4oE9U+BhZGrhzYmmO+3K5jRCGX2d8pqn+SON+SCBBfxzE27Hzl/mUKJg/OmMcxF/XtM65ojNEfuUifR/dPq2BazVPOTfimx/a6kU/Rzvw+qpFVLFNhE8CZ1I7wYpZLYyfqLUFIxjum70GAXgIaULzxzEMVgVtQS4j0w=
