[playout]

atari_check = 0.743349
captures_probability = 0.44147
ladder_check = 0.702563
large_pattern_factor = 315.093
large_pattern_probability = 0.386782
last_moves_for_heuristics = 2
pattern_probability = 0.868737
play_in_middle_of_eye = 1.0

[priors]

best_move_factor = 1.0
capture_many = 30
capture_one = 15
empty = 20
large_pattern_factor = 143
neutral_plays = 10
neutral_wins = 5
self_atari = 10
small_patterns = 14

[time_control]

c = 0.928949
fastplay_threshold = 0.811985
fastplay_budget = 0.305821
min_stones = 24

[tree]

expand_after = 6
rave_equiv = 24.8829
score_weight = 0.0653414

[scoring]

ownership_prior = 87
ownership_cutoff = 0.892867
playouts = 10000
resignation_percentage = 0.15
